# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 083a53379be0e5f67b7bbca4e30677b25128275e9d625bdb87aed087702ec601d4665fbd951e4ee061dd212321d344195435898aa1166ea90dda574177ef259c

test:
  secret_key_base: ac40e4146036e0dc17768ccbde53e414a33ed6a6407addfdfc77a43121be87b0e3911d364b566c9946e5e7011a8a227872fb3a241915ff4dd016077ea47eb93b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
